### ISSUE TITLE
Suggesting Edit: Building Holochain Apps - Bridging

### ISSUE THREAD

**Issue by rlkelly** [holochain/docs-pages#152]
Page URL: http://developer.holochain.org/docs/guide/bridging/

`that allows a synchronous bidirectional transfer` should be asynchronous

**Comment by pdaoust** [comment]
I'm trying to figure out if it really is async or not :D A bridge call definitely blocks execution in the calling instance. I'm inclined to take the word out entirely. Thanks for the tip @rlkelly !

**Comment by pdaoust** [comment]
Fixed in d1fad72c6aceaba23344418691c6808e9976c74f .

**Comment by rlkelly** [comment]
Ok, so the way I'm reading this now is that it is a way to call a method in another app and then do something with the results in a blocking manner?  I think the additional sentence helps if that's the case, I just want to confirm I understand.

**Comment by pdaoust** [comment]
Right. The call completely blocks the caller until the callee function is done and returns a value. As yet, there isn't a good way of doing non-blocking data transfer between DNAs except by having the UI as a mediator.

Additionally, the 'bidirectional' thing comes with a big caveat: bridge dependencies are set up one-way, so that only the dependant can call the dependency. This makes for a disciplined dependency graph, but it means the dependency can't trigger an action in a dependant. This makes no sense even to me, so let's explain it with an example:

1. There's a currency DNA; let's call it HoloCredit.
2. There's a tipping DNA; let's call it CoffeeMoney.
3. CoffeeMoney depends on HoloCredit, so it sets up a bridge dependency between the two DNAs in the user's conductor.
4. Alice wants to tip Bob 5.5 HoloCredits for a well-written article on weedeater maintenance, so her CoffeeMoney instance calls her HoloCredit instance's `send_money(bob_address, 5.5)`.
5. Alice's CoffeeMoney instance is now blocked and waiting for her HoloCredit instance to do its thing and return a successful result.
6. So far, so good. HoloCredit shouldn't have to know about all the things that depend on it -- that would introduce a circular dependency, which is messy territory.
7. But what if Bob is offline? It'd be nice for Alice to at least be able to initiate the transaction, so that when Bob's online he can receive the 5.5 credits even if Alice is offline. But CoffeeMoney likes to know when the transaction has completed, so it can update its own records. Currently there's two options:
    * Alice's CoffeeMoney instance could poll her HoloCredit instance regularly, calling its `has_async_transaction_completed_yet(offer_address)` function.
    * Alice's HoloCredit instance could emit a `async_transaction_has_completed` signal when Bob accepts her tip, and her UI could listen for that signal and call her CoffeeMoney instance's `tip_finally_received` function.

I'm hoping that, in the future, DNAs will be able to listen signals too, so that in option 2 above the UI wouldn't have to be a mediator between the two apps. This would make things a lot more consistent.
