### ISSUE TITLE
Suggesting Edit: Hello Me Tutorial - test fails in Firefox, works in Chrome

### ISSUE THREAD

**Issue by mitra42** [holochain/docs-pages#163]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_me/
Using the code from the latter hello.js Check-your-code
In Firefox, the result of 
```
var address = document.getElementById('address_in').value;
```
is 
`" Address: QmaijZvaP2BKj5r14KLTaB2yF4V1hukkSg7cJG6nLtNFSL"` 
While in Chrome its
`"QmaijZvaP2BKj5r14KLTaB2yF4V1hukkSg7cJG6nLtNFSL"`

In Firefox it of course fails to retrieve that, while Chrome works fine.

I don't understand why Firefox behaves like this ... as the DOM looks like 
```
<div>Address: <span id="address_output"> QmaijZvaP2BKj5r14KLTaB2yF4V1hukkSg7cJG6nLtNFSL</span></div>
```
But its 100% repeatable and will leave you to debug it ....

**Comment by pdaoust** [comment]
I can't repeat this when I download the code directly from `freesig/cc_tuts` (branch `hello_me`) or when I copy/paste from the final version of the tutorial page. So I'm wondering if it was due to some bugs in the tutorial parser/compiler that've since been resolved.

(I do notice one issue though: When you double-click on the hash, Firefox selects the leading space, which gets copied into the 'Retrieve Person' textbox. This doesn't happen on Chrome. I'll leave this issue open until I add a `.trim()` to the line you've quoted @mitra42 .

**Comment by pdaoust** [comment]
Closing -- feel free to re-open if it's not solved @mitra42
