### ISSUE TITLE
Suggesting Edit: Simple Micro Blog Tutorial

### ISSUE THREAD

**Issue by Chris39704** [holochain/docs-pages#188]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/simple_micro_blog/

Similar to Hello World, Terminal 3 for Agent Bob needs "--port 8889" otherwise the conductor will error seeing port 8888 already in use.

**Comment by pdaoust** [comment]
Similar to #187

**Comment by pdaoust** [comment]
Fixed by #186

**Comment by pdaoust** [comment]
Apparently `hc run` automatically binds to the next available port number after `8888` (same for the RPC port `50000`), so this should work without explicit port numbers. However, I'm fixing this (see #182) so that it fails early and alerts the reader that the following URLs are probably not gonna work.
