### ISSUE TITLE
Confusing explanations about `native_type` in first_steps

### ISSUE THREAD

**Issue by niwolive** [holochain/docs-pages#20]
### What is the URL of the page with the issue?
https://developer.holochain.org/guide/latest/first_steps.html#adding-some-entries

### What specific instruction was incorrect, or did not work for you?

> Take note of the native_type field of the macro which gives which Rust struct represents the entry type.
(see [source](https://github.com/holochain/docs-pages/blob/58a45d94a880ee673ab8fd85c19333135074de5b/guide/0.0.13-alpha1/first_steps.html#L295))

The example above this line does not contain any `native_type` field, so I'm very confused and not sure what I should take note of.

Probably the code code updated and not the text or vis-versa?

**Comment by Connoropolous** [comment]
Hi @niwolive 

Yes, sorry about that. As noted at the top of the page, the tutorial on that page is only up to date for version 0.0.9

Because we are doing weekly releases, it is too often that the tutorial is changing to update it weekly, so instead we have a cycle of updating it that is a little bit longer than that. We will be updating it to the latest version, which you're likely to be running, very soon.

**Comment by niwolive** [comment]
Great, thank you so much for your work.

**Comment by jamesray1** [comment]
Same thing with `ctx` mentioned in the same para.
