### ISSUE TITLE
Can we add instructions on how to install a specific versions/releases of "hc" and "holochain"

### ISSUE THREAD

**Issue by tommycp3** [holochain/docs-pages#30]
### What is the URL of the page with the issue?
https://developer.holochain.org/start.html - under heading: "Permanently install holochain tools (optional)"

### What specific instruction was incorrect, or did not work for you?
As the holochain team releases new versions this creates breaking changes, during the devcamps we will choose to stick to a specific version of holochain and hc and would like this the ability to install specific versions via nix-env

### What are the details of your platform?
N/A

Can we modify the holochain install documentation to what is suggested in the image below?
![2019-07-24_22-25-00](https://user-images.githubusercontent.com/13199826/62001238-9bfae080-b12f-11e9-8a9a-26a09ed006e7.png)

**Comment by dhtnetwork** [comment]
Update: It’s possible to target any version of Holonix with the direct github link such as: https://github.com/holochain/holonix/tarball/<x.y.z>

Also, to address the issues related to releases/breaking changes, our devs are committed to ensuring that releases will not ship if the test suite to Holonix breaks.  

Comment: “we will add a test suite to holonix that simulates the quick start guide and we won't ship new versions if it breaks - kind of like the "app spec tests" for core”

Please let us know if this resolves your request so that we can close it out.  Thank you.

**Comment by dhtnetwork** [comment]
You can track the status of this effort here: https://github.com/holochain/holonix/issues/26

**Comment by tommycp3** [comment]
So I've currently got holochain 0.0.25-alpha1 and hc 0.0.25-alpha1
 installed and I want to downgrade to https://github.com/holochain/holonix/releases/tag/0.0.22

so I presume I run:
`nix-env -f https://github.com/holochain/holonix/releases/tag/0.0.22`

however I get the following error.
![2019-08-01_06-57-49](https://user-images.githubusercontent.com/13199826/62247700-b253b580-b429-11e9-9be9-43c379ea80cf.png)



I understand there are holochain-rust versions here: https://github.com/holochain/holochain-rust/releases

then thee are nix/holonix versions here: https://github.com/holochain/holonix/releases

getting a little confused what version of holochain and hc will be installed with each holonix release.

sorry I'm not very good with understanding how Nix works yet.  do you know what I'm doing wrong?
thanks

**Comment by dhtnetwork** [comment]
Hi any reason why you need to downgrade to 0.0.22-alpha1?  
- It's best to use holochain.love (see the steps from the quick start page). https://developer.holochain.org/start.html
- If you use holochain.love you get the newest release. You'll need to make sure in your cargo toml you also point to the newest release otherwise things will get mixed up.  
- May be try to uninstall and install again? Is there a missing step from the quick start page?  
- More info about Holonix: "Holonix allows you to simply install nix-shell to set up the environment and all the dependencies will be taken care of, with no need to maintain or fix installation scripts."
https://medium.com/holochain/introducing-holoportos-and-the-three-major-benefits-of-holonix-4132a2ad5e72

**Comment by dhtnetwork** [comment]
FYI Holonix 0.0.22 includes the latest holochain-rust v0.0.25-alpha1

**Comment by dhtnetwork** [comment]
@tommycp3 I believe this issue has been resolved.  Let us know if you need additional support.
